# Definicion

In [1]:
x = "hello world"
y = 1
print(x)

hello world

In [2]:
type(x)

str

In [4]:
x = "hello\nworld\tbye"
print(x)

hello
world	bye

In [6]:
x = "hello\\nworld"
print(x)

hello\nworld

In [5]:
x = r"hello\nworld"
print(x)

hello\nworld

In [7]:
x = "hola" + "bye"
print(x)

holabye

In [8]:
x = 'hola'
print(x)

hola

In [9]:
'hola' == "hola"

True

In [11]:
x = """
hola
mu\nndo
saludos
"""
print(x)

hola
mu
ndo
saludos

In [12]:
x = r"""
hola
mu\nndo
saludos
"""
print(x)

hola
mu\nndo
saludos

In [13]:
x = b"hello"
print(x)

b'hello'

In [14]:
x[0]

104

In [15]:
x = "hello %d" % 2
print(x)

hello 2

In [16]:
x = "hello {var}"

In [17]:
x

'hello {var}'

In [18]:
x.format(var="world")

'hello world'

In [20]:
var = "world"
x = f"hello {var}"
print(x)

hello world

In [22]:
loss = 0.128347192384712983434
print(f"Loss: {loss:.2f}")

Loss: 0.13

In [24]:
header = ["nombre", "edad"]
x = [
    ("Santiago", 22),
    ("Andres", 22),
    ("Ivan", 23),
    ("Hernan", 30),
    ("Andres", 28)
]

In [25]:
print(x)

[('Santiago', 22), ('Andres', 22), ('Ivan', 23), ('Hernan', 30), ('Andres', 28)]

In [26]:
import pandas as pd
df = pd.DataFrame(data=x, columns=header)
df

     nombre  edad
0  Santiago    22
1    Andres    22
2      Ivan    23
3    Hernan    30
4    Andres    28

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df, *['edad'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df, *['edad'], **{})
chart

import numpy as np
from google.colab import autoviz

def categorical_histogram(df, colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  df.groupby(colname).size().plot(kind='barh', color=sns.palettes.mpl_palette(mpl_palette_name), figsize=(8*figscale, 4.8*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(df, *['nombre'], **{})
chart

import numpy as np
from google.colab import autoviz

def violin_plot(df, value_colname, facet_colname, figscale=1, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (12 * figscale, 1.2 * figscale * len(df[facet_colname].unique()))
  plt.figure(figsize=figsize)
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(df, *['edad', 'nombre'], **{'inner': 'stick'})
chart

In [28]:
for row in x:
    print(row[0], row[1])

Santiago 22
Andres 22
Ivan 23
Hernan 30
Andres 28

In [31]:
table_format = "|{var1}|{var2}|"
print(table_format.format(var1=header[0], var2=header[1]))
for row in x:
    print(table_format.format(var1=row[0], var2=row[1]))

|nombre|edad|
|Santiago|22|
|Andres|22|
|Ivan|23|
|Hernan|30|
|Andres|28|

In [36]:
print(f"|{header[0]:<20}|{header[1]:<20}|")
for row in x:
    print(f"|{row[0]:<20}|{row[1]:<20}|")

|nombre              |edad                |
|Santiago            |22                  |
|Andres              |22                  |
|Ivan                |23                  |
|Hernan              |30                  |
|Andres              |28                  |

In [ ]:
x = """
You're an AI assistant who helps with math problems

Previous conversation:
{conv}

New message:
{mesg}

AI message:
"""

# Operaciones

In [37]:
"hola" + " " + "mundo"

'hola mundo'

In [38]:
"hola" * 5

'holaholaholaholahola'

In [39]:
x = "hello"
x[:3]

'hel'

In [41]:
x = "hello"
y = "Hello"
x == y

False

In [43]:
x > y

True

In [44]:
"a" < "b"

True

# Metodos

In [45]:
x = "hello" +\
    "world" +\
    "test"

In [46]:
print(x)

helloworldtest

In [47]:
x = (
    "hello"
    "world"
    "test"
)

In [48]:
print(x)

helloworldtest

In [49]:
x = "hello world"
x.title()

'Hello World'

In [50]:
x.capitalize()

'Hello world'

In [51]:
x.upper()

'HELLO WORLD'

In [52]:
x.lower()

'hello world'

In [56]:
x = ["hello", "world", "test"]
" - ".join(x)

'hello - world - test'

In [59]:
!wget 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv' -O data.csv

--2023-09-15 00:36:01--  https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 60302 (59K) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]  58.89K  --.-KB/s    in 0.01s

2023-09-15 00:36:01 (5.07 MB/s) - ‘data.csv’ saved [60302/60302]

In [60]:
!ls -sh

total 64K
 60K data.csv  4.0K sample_data

In [61]:
df = pd.read_csv("data.csv")

In [62]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [63]:
with open("data.csv") as f:
    data = f.read()

In [86]:
from typing import Dict, List, Type
from pathlib import Path
from dataclasses import dataclass

DataType = int | float | str

@dataclass
class Row:
    fields: Dict[str, DataType]

@dataclass
class Table:
    rows: List[Row]

In [92]:
Schema = Dict[str, Type]
def parse_row(line: str, schema: Schema) -> Row | None:
    try:
        vals = line.split('"')
        all_vals = []
        all_vals.extend(vals[0][:-1].split(","))
        all_vals.append(vals[1])
        all_vals.extend(vals[2][1:].split(","))
        types = schema.values()
        parsed_vals = list(map(lambda cats: cats[0](cats[1]), zip(types, all_vals)))
        return Row(
            fields = dict(zip(schema.keys(), parsed_vals))
        )
    except:
        return None

parse_row('1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,,S', schema)

Row(fields={'PassengerId': 1, 'Survived': True, 'Pclass': 3, 'Name': 'Braund, Mr. Owen Harris', 'Sex': 'male', 'Age': 22, 'SibSp': 1, 'Parch': 0, 'Ticket': 'A/5 21171', 'Fare': 7.25, 'Cabin': '', 'Embarked': 'S'})

In [97]:
def load_csv(path: Path, schema: Schema) -> Table:
    with open(path, 'r') as f:
        data = f.read()
    lines = data.split("\n")
    rows = map(lambda line: parse_row(line, schema), lines)
    clean_rows = list(filter(lambda row: row is not None, rows))
    return Table(rows=clean_rows)

In [98]:
path = Path("data.csv")
schema = {
    "PassengerId": int,
    "Survived": bool,
    "Pclass": int,
    "Name": str,
    "Sex": str,
    "Age": int,
    "SibSp": int,
    "Parch": int,
    "Ticket": str,
    "Fare": float,
    "Cabin": str,
    "Embarked": str
}
load_csv(path, schema)

Table(rows=[Row(fields={'PassengerId': 1, 'Survived': True, 'Pclass': 3, 'Name': 'Braund, Mr. Owen Harris', 'Sex': 'male', 'Age': 22, 'SibSp': 1, 'Parch': 0, 'Ticket': 'A/5 21171', 'Fare': 7.25, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 2, 'Survived': True, 'Pclass': 1, 'Name': 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'Sex': 'female', 'Age': 38, 'SibSp': 1, 'Parch': 0, 'Ticket': 'PC 17599', 'Fare': 71.2833, 'Cabin': 'C85', 'Embarked': 'C'}), Row(fields={'PassengerId': 3, 'Survived': True, 'Pclass': 3, 'Name': 'Heikkinen, Miss. Laina', 'Sex': 'female', 'Age': 26, 'SibSp': 0, 'Parch': 0, 'Ticket': 'STON/O2. 3101282', 'Fare': 7.925, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 4, 'Survived': True, 'Pclass': 1, 'Name': 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'Sex': 'female', 'Age': 35, 'SibSp': 1, 'Parch': 0, 'Ticket': '113803', 'Fare': 53.1, 'Cabin': 'C123', 'Embarked': 'S'}), Row(fields={'PassengerId': 5, 'Survived': True, 'Pclass': 3, 'Name': 'Allen, Mr. William Henry', 'Sex': 'male', 'Age': 35, 'SibSp': 0, 'Parch': 0, 'Ticket': '373450', 'Fare': 8.05, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 7, 'Survived': True, 'Pclass': 1, 'Name': 'McCarthy, Mr. Timothy J', 'Sex': 'male', 'Age': 54, 'SibSp': 0, 'Parch': 0, 'Ticket': '17463', 'Fare': 51.8625, 'Cabin': 'E46', 'Embarked': 'S'}), Row(fields={'PassengerId': 8, 'Survived': True, 'Pclass': 3, 'Name': 'Palsson, Master. Gosta Leonard', 'Sex': 'male', 'Age': 2, 'SibSp': 3, 'Parch': 1, 'Ticket': '349909', 'Fare': 21.075, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 9, 'Survived': True, 'Pclass': 3, 'Name': 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)', 'Sex': 'female', 'Age': 27, 'SibSp': 0, 'Parch': 2, 'Ticket': '347742', 'Fare': 11.1333, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 10, 'Survived': True, 'Pclass': 2, 'Name': 'Nasser, Mrs. Nicholas (Adele Achem)', 'Sex': 'female', 'Age': 14, 'SibSp': 1, 'Parch': 0, 'Ticket': '237736', 'Fare': 30.0708, 'Cabin': '', 'Embarked': 'C'}), Row(fields={'PassengerId': 11, 'Survived': True, 'Pclass': 3, 'Name': 'Sandstrom, Miss. Marguerite Rut', 'Sex': 'female', 'Age': 4, 'SibSp': 1, 'Parch': 1, 'Ticket': 'PP 9549', 'Fare': 16.7, 'Cabin': 'G6', 'Embarked': 'S'}), Row(fields={'PassengerId': 12, 'Survived': True, 'Pclass': 1, 'Name': 'Bonnell, Miss. Elizabeth', 'Sex': 'female', 'Age': 58, 'SibSp': 0, 'Parch': 0, 'Ticket': '113783', 'Fare': 26.55, 'Cabin': 'C103', 'Embarked': 'S'}), Row(fields={'PassengerId': 13, 'Survived': True, 'Pclass': 3, 'Name': 'Saundercock, Mr. William Henry', 'Sex': 'male', 'Age': 20, 'SibSp': 0, 'Parch': 0, 'Ticket': 'A/5. 2151', 'Fare': 8.05, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 14, 'Survived': True, 'Pclass': 3, 'Name': 'Andersson, Mr. Anders Johan', 'Sex': 'male', 'Age': 39, 'SibSp': 1, 'Parch': 5, 'Ticket': '347082', 'Fare': 31.275, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 15, 'Survived': True, 'Pclass': 3, 'Name': 'Vestrom, Miss. Hulda Amanda Adolfina', 'Sex': 'female', 'Age': 14, 'SibSp': 0, 'Parch': 0, 'Ticket': '350406', 'Fare': 7.8542, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 16, 'Survived': True, 'Pclass': 2, 'Name': 'Hewlett, Mrs. (Mary D Kingcome) ', 'Sex': 'female', 'Age': 55, 'SibSp': 0, 'Parch': 0, 'Ticket': '248706', 'Fare': 16.0, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 17, 'Survived': True, 'Pclass': 3, 'Name': 'Rice, Master. Eugene', 'Sex': 'male', 'Age': 2, 'SibSp': 4, 'Parch': 1, 'Ticket': '382652', 'Fare': 29.125, 'Cabin': '', 'Embarked': 'Q'}), Row(fields={'PassengerId': 19, 'Survived': True, 'Pclass': 3, 'Name': 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)', 'Sex': 'female', 'Age': 31, 'SibSp': 1, 'Parch': 0, 'Ticket': '345763', 'Fare': 18.0, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 21, 'Survived': True, 'Pclass': 2, 'Name': 'Fynney, Mr. Joseph J', 'Sex': 'male', 'Age': 35, 'SibSp': 0, 'Parch': 0, 'Ticket': '239865', 'Fare': 26.0, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 22, 'Survived': True, 'Pclass': 2, 'Name': 'Beesley, Mr. Lawrence', 'Sex': 'male', 'Age': 34, 'SibSp': 0, 'Parch': 0, 'Ticket': '248698', 'Fare': 13.0, 'Cabin': 'D56', 'Embarked': 'S'}), Row(fields={'PassengerId': 23, 'Survived': True, 'Pclass': 3, 'Name': 'McGowan, Miss. Anna ', 'Sex': ''}), Row(fields={'PassengerId': 24, 'Survived': True, 'Pclass': 1, 'Name': 'Sloper, Mr. William Thompson', 'Sex': 'male', 'Age': 28, 'SibSp': 0, 'Parch': 0, 'Ticket': '113788', 'Fare': 35.5, 'Cabin': 'A6', 'Embarked': 'S'}), Row(fields={'PassengerId': 25, 'Survived': True, 'Pclass': 3, 'Name': 'Palsson, Miss. Torborg Danira', 'Sex': 'female', 'Age': 8, 'SibSp': 3, 'Parch': 1, 'Ticket': '349909', 'Fare': 21.075, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 26, 'Survived': True, 'Pclass': 3, 'Name': 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)', 'Sex': 'female', 'Age': 38, 'SibSp': 1, 'Parch': 5, 'Ticket': '347077', 'Fare': 31.3875, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 28, 'Survived': True, 'Pclass': 1, 'Name': 'Fortune, Mr. Charles Alexander', 'Sex': 'male', 'Age': 19, 'SibSp': 3, 'Parch': 2, 'Ticket': '19950', 'Fare': 263.0, 'Cabin': 'C23 C25 C27', 'Embarked': 'S'}), Row(fields={'PassengerId': 29, 'Survived': True, 'Pclass': 3, 'Name': "O'Dwyer, Miss. Ellen ", 'Sex': ''}), Row(fields={'PassengerId': 31, 'Survived': True, 'Pclass': 1, 'Name': 'Uruchurtu, Don. Manuel E', 'Sex': 'male', 'Age': 40, 'SibSp': 0, 'Parch': 0, 'Ticket': 'PC 17601', 'Fare': 27.7208, 'Cabin': '', 'Embarked': 'C'}), Row(fields={'PassengerId': 34, 'Survived': True, 'Pclass': 2, 'Name': 'Wheadon, Mr. Edward H', 'Sex': 'male', 'Age': 66, 'SibSp': 0, 'Parch': 0, 'Ticket': 'C.A. 24579', 'Fare': 10.5, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 35, 'Survived': True, 'Pclass': 1, 'Name': 'Meyer, Mr. Edgar Joseph', 'Sex': 'male', 'Age': 28, 'SibSp': 1, 'Parch': 0, 'Ticket': 'PC 17604', 'Fare': 82.1708, 'Cabin': '', 'Embarked': 'C'}), Row(fields={'PassengerId': 36, 'Survived': True, 'Pclass': 1, 'Name': 'Holverson, Mr. Alexander Oskar', 'Sex': 'male', 'Age': 42, 'SibSp': 1, 'Parch': 0, 'Ticket': '113789', 'Fare': 52.0, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 38, 'Survived': True, 'Pclass': 3, 'Name': 'Cann, Mr. Ernest Charles', 'Sex': 'male', 'Age': 21, 'SibSp': 0, 'Parch': 0, 'Ticket': 'A./5. 2152', 'Fare': 8.05, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 39, 'Survived': True, 'Pclass': 3, 'Name': 'Vander Planke, Miss. Augusta Maria', 'Sex': 'female', 'Age': 18, 'SibSp': 2, 'Parch': 0, 'Ticket': '345764', 'Fare': 18.0, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 40, 'Survived': True, 'Pclass': 3, 'Name': 'Nicola-Yarred, Miss. Jamila', 'Sex': 'female', 'Age': 14, 'SibSp': 1, 'Parch': 0, 'Ticket': '2651', 'Fare': 11.2417, 'Cabin': '', 'Embarked': 'C'}), Row(fields={'PassengerId': 41, 'Survived': True, 'Pclass': 3, 'Name': 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)', 'Sex': 'female', 'Age': 40, 'SibSp': 1, 'Parch': 0, 'Ticket': '7546', 'Fare': 9.475, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 42, 'Survived': True, 'Pclass': 2, 'Name': 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)', 'Sex': 'female', 'Age': 27, 'SibSp': 1, 'Parch': 0, 'Ticket': '11668', 'Fare': 21.0, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 44, 'Survived': True, 'Pclass': 2, 'Name': 'Laroche, Miss. Simonne Marie Anne Andree', 'Sex': 'female', 'Age': 3, 'SibSp': 1, 'Parch': 2, 'Ticket': 'SC/Paris 2123', 'Fare': 41.5792, 'Cabin': '', 'Embarked': 'C'}), Row(fields={'PassengerId': 45, 'Survived': True, 'Pclass': 3, 'Name': 'Devaney, Miss. Margaret Delia', 'Sex': 'female', 'Age': 19, 'SibSp': 0, 'Parch': 0, 'Ticket': '330958', 'Fare': 7.8792, 'Cabin': '', 'Embarked': 'Q'}), Row(fields={'PassengerId': 50, 'Survived': True, 'Pclass': 3, 'Name': 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)', 'Sex': 'female', 'Age': 18, 'SibSp': 1, 'Parch': 0, 'Ticket': '349237', 'Fare': 17.8, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 51, 'Survived': True, 'Pclass': 3, 'Name': 'Panula, Master. Juha Niilo', 'Sex': 'male', 'Age': 7, 'SibSp': 4, 'Parch': 1, 'Ticket': '3101295', 'Fare': 39.6875, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 52, 'Survived': True, 'Pclass': 3, 'Name': 'Nosworthy, Mr. Richard Cater', 'Sex': 'male', 'Age': 21, 'SibSp': 0, 'Parch': 0, 'Ticket': 'A/4. 39886', 'Fare': 7.8, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 53, 'Survived': True, 'Pclass': 1, 'Name': 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 'Sex': 'female', 'Age': 49, 'SibSp': 1, 'Parch': 0, 'Ticket': 'PC 17572', 'Fare': 76.7292, 'Cabin': 'D33', 'Embarked': 'C'}), Row(fields={'PassengerId': 54, 'Survived': True, 'Pclass': 2, 'Name': 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)', 'Sex': 'female', 'Age': 29, 'SibSp': 1, 'Parch': 0, 'Ticket': '2926', 'Fare': 26.0, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 55, 'Survived': True, 'Pclass': 1, 'Name': 'Ostby, Mr. Engelhart Cornelius', 'Sex': 'male', 'Age': 65, 'SibSp': 0, 'Parch': 1, 'Ticket': '113509', 'Fare': 61.9792, 'Cabin': 'B30', 'Embarked': 'C'}), Row(fields={'PassengerId': 57, 'Survived': True, 'Pclass': 2, 'Name': 'Rugg, Miss. Emily', 'Sex': 'female', 'Age': 21, 'SibSp': 0, 'Parch': 0, 'Ticket': 'C.A. 31026', 'Fare': 10.5, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 59, 'Survived': True, 'Pclass': 2, 'Name': 'West, Miss. Constance Mirium', 'Sex': 'female', 'Age': 5, 'SibSp': 1, 'Parch': 2, 'Ticket': 'C.A. 34651', 'Fare': 27.75, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 60, 'Survived': True, 'Pclass': 3, 'Name': 'Goodwin, Master. William Frederick', 'Sex': 'male', 'Age': 11, 'SibSp': 5, 'Parch': 2, 'Ticket': 'CA 2144', 'Fare': 46.9, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 61, 'Survived': True, 'Pclass': 3, 'Name': 'Sirayanian, Mr. Orsen', 'Sex': 'male', 'Age': 22, 'SibSp': 0, 'Parch': 0, 'Ticket': '2669', 'Fare': 7.2292, 'Cabin': '', 'Embarked': 'C'}), Row(fields={'PassengerId': 62, 'Survived': True, 'Pclass': 1, 'Name': 'Icard, Miss. Amelie', 'Sex': 'female', 'Age': 38, 'SibSp': 0, 'Parch': 0, 'Ticket': '113572', 'Fare': 80.0, 'Cabin': 'B28', 'Embarked': ''}), Row(fields={'PassengerId': 63, 'Survived': True, 'Pclass': 1, 'Name': 'Harris, Mr. Henry Birkhardt', 'Sex': 'male', 'Age': 45, 'SibSp': 1, 'Parch': 0, 'Ticket': '36973', 'Fare': 83.475, 'Cabin': 'C83', 'Embarked': 'S'}), Row(fields={'PassengerId': 64, 'Survived': True, 'Pclass': 3, 'Name': 'Skoog, Master. Harald', 'Sex': 'male', 'Age': 4, 'SibSp': 3, 'Parch': 2, 'Ticket': '347088', 'Fare': 27.9, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 67, 'Survived': True, 'Pclass': 2, 'Name': 'Nye, Mrs. (Elizabeth Ramell)', 'Sex': 'female', 'Age': 29, 'SibSp': 0, 'Parch': 0, 'Ticket': 'C.A. 29395', 'Fare': 10.5, 'Cabin': 'F33', 'Embarked': 'S'}), Row(fields={'PassengerId': 68, 'Survived': True, 'Pclass': 3, 'Name': 'Crease, Mr. Ernest James', 'Sex': 'male', 'Age': 19, 'SibSp': 0, 'Parch': 0, 'Ticket': 'S.P. 3464', 'Fare': 8.1583, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 69, 'Survived': True, 'Pclass': 3, 'Name': 'Andersson, Miss. Erna Alexandra', 'Sex': 'female', 'Age': 17, 'SibSp': 4, 'Parch': 2, 'Ticket': '3101281', 'Fare': 7.925, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 70, 'Survived': True, 'Pclass': 3, 'Name': 'Kink, Mr. Vincenz', 'Sex': 'male', 'Age': 26, 'SibSp': 2, 'Parch': 0, 'Ticket': '315151', 'Fare': 8.6625, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 71, 'Survived': True, 'Pclass': 2, 'Name': 'Jenkin, Mr. Stephen Curnow', 'Sex': 'male', 'Age': 32, 'SibSp': 0, 'Parch': 0, 'Ticket': 'C.A. 33111', 'Fare': 10.5, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 72, 'Survived': True, 'Pclass': 3, 'Name': 'Goodwin, Miss. Lillian Amy', 'Sex': 'female', 'Age': 16, 'SibSp': 5, 'Parch': 2, 'Ticket': 'CA 2144', 'Fare': 46.9, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 73, 'Survived': True, 'Pclass': 2, 'Name': 'Hood, Mr. Ambrose Jr', 'Sex': 'male', 'Age': 21, 'SibSp': 0, 'Parch': 0, 'Ticket': 'S.O.C. 14879', 'Fare': 73.5, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 74, 'Survived': True, 'Pclass': 3, 'Name': 'Chronopoulos, Mr. Apostolos', 'Sex': 'male', 'Age': 26, 'SibSp': 1, 'Parch': 0, 'Ticket': '2680', 'Fare': 14.4542, 'Cabin': '', 'Embarked': 'C'}), Row(fields={'PassengerId': 75, 'Survived': True, 'Pclass': 3, 'Name': 'Bing, Mr. Lee', 'Sex': 'male', 'Age': 32, 'SibSp': 0, 'Parch': 0, 'Ticket': '1601', 'Fare': 56.4958, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 76, 'Survived': True, 'Pclass': 3, 'Name': 'Moen, Mr. Sigurd Hansen', 'Sex': 'male', 'Age': 25, 'SibSp': 0, 'Parch': 0, 'Ticket': '348123', 'Fare': 7.65, 'Cabin': 'F G73', 'Embarked': 'S'}), Row(fields={'PassengerId': 80, 'Survived': True, 'Pclass': 3, 'Name': 'Dowdell, Miss. Elizabeth', 'Sex': 'female', 'Age': 30, 'SibSp': 0, 'Parch': 0, 'Ticket': '364516', 'Fare': 12.475, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 81, 'Survived': True, 'Pclass': 3, 'Name': 'Waelens, Mr. Achille', 'Sex': 'male', 'Age': 22, 'SibSp': 0, 'Parch': 0, 'Ticket': '345767', 'Fare': 9.0, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 82, 'Survived': True, 'Pclass': 3, 'Name': 'Sheerlinck, Mr. Jan Baptist', 'Sex': 'male', 'Age': 29, 'SibSp': 0, 'Parch': 0, 'Ticket': '345779', 'Fare': 9.5, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 84, 'Survived': True, 'Pclass': 1, 'Name': 'Carrau, Mr. Francisco M', 'Sex': 'male', 'Age': 28, 'SibSp': 0, 'Parch': 0, 'Ticket': '113059', 'Fare': 47.1, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 85, 'Survived': True, 'Pclass': 2, 'Name': 'Ilett, Miss. Bertha', 'Sex': 'female', 'Age': 17, 'SibSp': 0, 'Parch': 0, 'Ticket': 'SO/C 14885', 'Fare': 10.5, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 86, 'Survived': True, 'Pclass': 3, 'Name': 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)', 'Sex': 'female', 'Age': 33, 'SibSp': 3, 'Parch': 0, 'Ticket': '3101278', 'Fare': 15.85, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 87, 'Survived': True, 'Pclass': 3, 'Name': 'Ford, Mr. William Neal', 'Sex': 'male', 'Age': 16, 'SibSp': 1, 'Parch': 3, 'Ticket': 'W./C. 6608', 'Fare': 34.375, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 89, 'Survived': True, 'Pclass': 1, 'Name': 'Fortune, Miss. Mabel Helen', 'Sex': 'female', 'Age': 23, 'SibSp': 3, 'Parch': 2, 'Ticket': '19950', 'Fare': 263.0, 'Cabin': 'C23 C25 C27', 'Embarked': 'S'}), Row(fields={'PassengerId': 90, 'Survived': True, 'Pclass': 3, 'Name': 'Celotti, Mr. Francesco', 'Sex': 'male', 'Age': 24, 'SibSp': 0, 'Parch': 0, 'Ticket': '343275', 'Fare': 8.05, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 91, 'Survived': True, 'Pclass': 3, 'Name': 'Christmann, Mr. Emil', 'Sex': 'male', 'Age': 29, 'SibSp': 0, 'Parch': 0, 'Ticket': '343276', 'Fare': 8.05, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 92, 'Survived': True, 'Pclass': 3, 'Name': 'Andreasson, Mr. Paul Edvin', 'Sex': 'male', 'Age': 20, 'SibSp': 0, 'Parch': 0, 'Ticket': '347466', 'Fare': 7.8542, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 93, 'Survived': True, 'Pclass': 1, 'Name': 'Chaffee, Mr. Herbert Fuller', 'Sex': 'male', 'Age': 46, 'SibSp': 1, 'Parch': 0, 'Ticket': 'W.E.P. 5734', 'Fare': 61.175, 'Cabin': 'E31', 'Embarked': 'S'}), Row(fields={'PassengerId': 94, 'Survived': True, 'Pclass': 3, 'Name': 'Dean, Mr. Bertram Frank', 'Sex': 'male', 'Age': 26, 'SibSp': 1, 'Parch': 2, 'Ticket': 'C.A. 2315', 'Fare': 20.575, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 95, 'Survived': True, 'Pclass': 3, 'Name': 'Coxon, Mr. Daniel', 'Sex': 'male', 'Age': 59, 'SibSp': 0, 'Parch': 0, 'Ticket': '364500', 'Fare': 7.25, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 97, 'Survived': True, 'Pclass': 1, 'Name': 'Goldschmidt, Mr. George B', 'Sex': 'male', 'Age': 71, 'SibSp': 0, 'Parch': 0, 'Ticket': 'PC 17754', 'Fare': 34.6542, 'Cabin': 'A5', 'Embarked': 'C'}), Row(fields={'PassengerId': 98, 'Survived': True, 'Pclass': 1, 'Name': 'Greenfield, Mr. William Bertram', 'Sex': 'male', 'Age': 23, 'SibSp': 0, 'Parch': 1, 'Ticket': 'PC 17759', 'Fare': 63.3583, 'Cabin': 'D10 D12', 'Embarked': 'C'}), Row(fields={'PassengerId': 99, 'Survived': True, 'Pclass': 2, 'Name': 'Doling, Mrs. John T (Ada Julia Bone)', 'Sex': 'female', 'Age': 34, 'SibSp': 0, 'Parch': 1, 'Ticket': '231919', 'Fare': 23.0, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 100, 'Survived': True, 'Pclass': 2, 'Name': 'Kantor, Mr. Sinai', 'Sex': 'male', 'Age': 34, 'SibSp': 1, 'Parch': 0, 'Ticket': '244367', 'Fare': 26.0, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 101, 'Survived': True, 'Pclass': 3, 'Name': 'Petranec, Miss. Matilda', 'Sex': 'female', 'Age': 28, 'SibSp': 0, 'Parch': 0, 'Ticket': '349245', 'Fare': 7.8958, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 102, 'Survived': True, 'Pclass': 3, 'Name': 'Petroff, Mr. Pastcho (', 'Sex': ''}), Row(fields={'PassengerId': 103, 'Survived': True, 'Pclass': 1, 'Name': 'White, Mr. Richard Frasar', 'Sex': 'male', 'Age': 21, 'SibSp': 0, 'Parch': 1, 'Ticket': '35281', 'Fare': 77.2875, 'Cabin': 'D26', 'Embarked': 'S'}), Row(fields={'PassengerId': 104, 'Survived': True, 'Pclass': 3, 'Name': 'Johansson, Mr. Gustaf Joel', 'Sex': 'male', 'Age': 33, 'SibSp': 0, 'Parch': 0, 'Ticket': '7540', 'Fare': 8.6542, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 105, 'Survived': True, 'Pclass': 3, 'Name': 'Gustafsson, Mr. Anders Vilhelm', 'Sex': 'male', 'Age': 37, 'SibSp': 2, 'Parch': 0, 'Ticket': '3101276', 'Fare': 7.925, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 106, 'Survived': True, 'Pclass': 3, 'Name': 'Mionoff, Mr. Stoytcho', 'Sex': 'male', 'Age': 28, 'SibSp': 0, 'Parch': 0, 'Ticket': '349207', 'Fare': 7.8958, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 107, 'Survived': True, 'Pclass': 3, 'Name': 'Salkjelsvik, Miss. Anna Kristine', 'Sex': 'female', 'Age': 21, 'SibSp': 0, 'Parch': 0, 'Ticket': '343120', 'Fare': 7.65, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 109, 'Survived': True, 'Pclass': 3, 'Name': 'Rekic, Mr. Tido', 'Sex': 'male', 'Age': 38, 'SibSp': 0, 'Parch': 0, 'Ticket': '349249', 'Fare': 7.8958, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 111, 'Survived': True, 'Pclass': 1, 'Name': 'Porter, Mr. Walter Chamberlain', 'Sex': 'male', 'Age': 47, 'SibSp': 0, 'Parch': 0, 'Ticket': '110465', 'Fare': 52.0, 'Cabin': 'C110', 'Embarked': 'S'}), Row(fields={'PassengerId': 113, 'Survived': True, 'Pclass': 3, 'Name': 'Barton, Mr. David John', 'Sex': 'male', 'Age': 22, 'SibSp': 0, 'Parch': 0, 'Ticket': '324669', 'Fare': 8.05, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 114, 'Survived': True, 'Pclass': 3, 'Name': 'Jussila, Miss. Katriina', 'Sex': 'female', 'Age': 20, 'SibSp': 1, 'Parch': 0, 'Ticket': '4136', 'Fare': 9.825, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 115, 'Survived': True, 'Pclass': 3, 'Name': 'Attalah, Miss. Malake', 'Sex': 'female', 'Age': 17, 'SibSp': 0, 'Parch': 0, 'Ticket': '2627', 'Fare': 14.4583, 'Cabin': '', 'Embarked': 'C'}), Row(fields={'PassengerId': 116, 'Survived': True, 'Pclass': 3, 'Name': 'Pekoniemi, Mr. Edvard', 'Sex': 'male', 'Age': 21, 'SibSp': 0, 'Parch': 0, 'Ticket': 'STON/O 2. 3101294', 'Fare': 7.925, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 118, 'Survived': True, 'Pclass': 2, 'Name': 'Turpin, Mr. William John Robert', 'Sex': 'male', 'Age': 29, 'SibSp': 1, 'Parch': 0, 'Ticket': '11668', 'Fare': 21.0, 'Cabin': '', 'Embarked': 'S'}), Row(fields={'PassengerId': 119, 'Survived': True, 'Pclass': 1, 'Name': 'Baxter, Mr. Quigg Edmond', 'Sex': 'male', '

In [99]:
64 / 4

16.0

In [100]:
!pip install gpt4all

Collecting gpt4all
  Downloading gpt4all-1.0.11-py3-none-manylinux1_x86_64.whl (6.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 9.9 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from gpt4all) (2.31.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from gpt4all) (4.66.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->gpt4all) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->gpt4all) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->gpt4all) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->gpt4all) (2023.7.22)
Installing collected packages: gpt4all
Successfully installed gpt4all-1.0.11

In [104]:
!git clone https://huggingface.co/juselara1/mlds7_models.git

Cloning into 'mlds7_models'...
remote: Enumerating objects: 6, done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 6
Unpacking objects: 100% (6/6), 803 bytes | 803.00 KiB/s, done.
Encountered 1 file(s) that may not have been copied correctly on Windows:
	ggml-model-gpt4all-falcon-q4_0.bin

See: `git lfs help smudge` for more details.

In [105]:
from gpt4all import GPT4All

In [106]:
llm = GPT4All(
    model_name="ggml-model-gpt4all-falcon-q4_0.bin",
    model_path="mlds7_models/"
    )

Found model file at  mlds7_models/ggml-model-gpt4all-falcon-q4_0.bin

In [108]:
conv = """
This is a conversation between a man and woman:

Man: Hello Marie.
Woman: Hi Frank, how are you?
Man: I'm doing well, and you?
Woman: """
llm.generate(conv)

"(sighs) Not so good.\nMan: What's wrong?\nWoman: Just feeling down today.\nMan: Is there anything I can do to help?\nWoman: No, it's just a rough day.\nMan: Well, let me know if you need anything.\nWoman: Thanks, Frank.\nMan: You're welcome. Take care.\nWoman: Bye.\n\nExplanation:\n\nThe man and woman are having a conversation about their current state of mind. The man asks the woman how she is doing, but she replies that she is feeling down today. The man offers to help her, but the woman declines saying it's just a rough day. The man thanks her for letting him know and tells her to take care."

In [109]:
x = """(sighs) Not so good.
Man: What's wrong?
Woman: Just feeling down today.
Man: Is there anything I can do to help?
Woman: No, it's just a rough day.
Man: Well, let me know if you need anything.
Woman: Thanks, Frank.
Man: You're welcome. Take care.
Woman: Bye.

Explanation:

The man and woman are having a conversation about their current state of mind. The man asks the woman how she is doing, but she replies that she is feeling down today. The man offers to help her, but the woman declines saying it's just a rough day. The man thanks her for letting him know and tells her to take care."""

In [110]:
print(x)

(sighs) Not so good.
Man: What's wrong?
Woman: Just feeling down today.
Man: Is there anything I can do to help?
Woman: No, it's just a rough day.
Man: Well, let me know if you need anything.
Woman: Thanks, Frank.
Man: You're welcome. Take care.
Woman: Bye.

Explanation:

The man and woman are having a conversation about their current state of mind. The man asks the woman how she is doing, but she replies that she is feeling down today. The man offers to help her, but the woman declines saying it's just a rough day. The man thanks her for letting him know and tells her to take care.